# This action runs lint checks and tests against the code.
name: Check and Test

# Controls when the action will run.
on:
  # Triggers the workflow on pushes to master and pull requests for any branch
  push:
    branches: [master]
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-and-test:
    name: Check and Test
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        mongodb_version: [stable, unstable]

    env:
      MONGODB_VERSION: ${{ matrix.mongodb_version }}
      MONGODB_TOPOLOGY: standalone

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
          node-version: 12.4.0

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests with Coverage
        run: npm run cover

      - name: Run Karma Tests
        run: npm run test:karma

      - name: Create Production Build
        run: npm run compile
        
      - name: Run Checks
        run: npm run check
