changelog:
  exclude:
    labels:
      - feature flagged
      - no release notes
  categories:
    - title: New Features
      labels:
        - feat
    - title: Bug Fixes
      labels:
        - fix