stepback: false
exec_timeout_secs: 5400
foliage_should_block_merges: false
ignore:
  - docs/**/*.md
  - AUTHORS
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - README.md
  - THIRD-PARTY-NOTICES.md
include:
  - filename: .evergreen/functions.yml
  - filename: .evergreen/buildvariants-and-tasks.yml
