stepback: false
exec_timeout_secs: 5400
unset_function_vars: true
ignore:
  - AUTHORS
  - THIRD-PARTY-NOTICES.md
include:
  - filename: .evergreen/functions.yml
  - filename: .evergreen/tasks.yml
  - filename: .evergreen/buildvariants.yml
