stepback: false
exec_timeout_secs: 86400
ignore:
  - AUTHORS
  - THIRD-PARTY-NOTICES.md
include:
  - filename: .evergreen/functions.yml
  - filename: .evergreen/tasks.yml
  - filename: .evergreen/buildvariants.yml