const base = require('@mongodb-js/knip-config-compass');
/** @type {import('knip').KnipConfig} */
module.exports = {
  ...base,
  entry: [...base.entry, 'src/index.tsx', 'test/**/*.test-d.{ts,tsx}'],
  project: [...base.project, 'test/**/*.{ts,tsx}'],
  ignoreDependencies: [
    ...base.ignoreDependencies,
    'tsd',
    'sinon',
    '@types/react',
    '@types/react-dom',
    '@types/express-http-proxy',
    'buffer',
    'events',
    'process',
    'util',
    '@mongodb-js/devtools-proxy-support',
    'mongodb',
    'bson',
    'aws-sdk',
    'browser-process-hrtime',
    'crypto-browserify',
    'debug',
    'dns-query',
    'is-ip',
    'mongodb-mcp-server',
    'os-browserify',
    'path-browserify',
    'readable-stream',
    'timers-browserify',
    'vm-browserify',
    'whatwg-url',
    'ws',
  ],
  ignoreBinaries: [...base.ignoreBinaries, 'tsc'],
};
