sudo: required
dist: trusty
language: node_js
node_js:
  - 7.9
env:
  matrix:
    - MONGODB_VERSION=3.6.x MONGODB_TOPOLOGY=standalone
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libkrb5-dev
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run check
script: npm run test
cache:
  directories:
    - $HOME/.electron
    - node_modules
