export type ConnectionScopeEvent =
  | 'Aggregation Canceled'
  | 'Aggregation Deleted'
  | 'Aggregation Edited'
  | 'Aggregation Executed'
  | 'Aggregation Explained'
  | 'Aggregation Opened'
  | 'Aggregation Saved'
  | 'Aggregation Saved As View'
  | 'Aggregation Side Panel Opened'
  | 'Aggregation Timed Out'
  | 'Aggregation Use Case Added'
  | 'Aggregation Use Case Saved'
  | 'AI Prompt Submitted'
  | 'AI Query Feedback'
  | 'AI Response Failed'
  | 'AI Response Generated'
  | 'Bulk Delete Executed'
  | 'Bulk Delete Opened'
  | 'Bulk Update Executed'
  | 'Bulk Update Favorited'
  | 'Bulk Update Opened'
  | 'Connection Attempt'
  | 'Connection Exported'
  | 'Connection Failed'
  | 'Connection Imported'
  | 'CurrentOp showOperationDetails'
  | 'DetailView hideOperationDetails'
  | 'DetailView killOp'
  | 'Document Cloned'
  | 'Document Copied'
  | 'Document Deleted'
  | 'Document Inserted'
  | 'Document Updated'
  | 'Editor Type Changed'
  | 'Explain Plan Executed'
  | 'Export Completed'
  | 'Export Opened'
  | 'Query Edited'
  | 'Query Executed'
  | 'Query History Closed'
  | 'Query History Favorite Added'
  | 'Query History Favorite Removed'
  | 'Query History Favorite Used'
  | 'Query History Favorites'
  | 'Query History Opened'
  | 'Query History Recent'
  | 'Query History Recent Used'
  | 'Query Results Refreshed'
  | 'Import Completed'
  | 'Import Error Log Opened'
  | 'Import Opened'
  | 'Index Create Opened'
  | 'Index Created'
  | 'Index Dropped'
  | 'Index Edited'
  | 'New Connection'
  | 'Performance Advisor Clicked'
  | 'Performance Paused'
  | 'Performance Resumed'
  | 'PipelineAI Feedback'
  | 'Schema Analyzed'
  | 'Schema Validation Added'
  | 'Schema Validation Edited'
  | 'Schema Validation Updated'
  | 'Shell Opened'
  | 'Switch View Type'
  | 'View Updated'
  // unsure
  | 'Focus Mode Closed'
  | 'Focus Mode Opened'
  | 'Guide Cue Dismissed'
  | 'Guide Cue Group Dismissed';

export type GeneralEvent =
  | 'Application Launched'
  | 'Application Restart Accepted'
  | 'Atlas Link Clicked'
  | 'Atlas Sign In Error'
  | 'Atlas Sign In Success'
  | 'Atlas Sign Out'
  | 'Autoupdate Accepted'
  | 'Autoupdate Disabled'
  | 'Autoupdate Dismissed'
  | 'Autoupdate Enabled'
  | 'My Queries Filter'
  | 'My Queries Search'
  | 'My Queries Sort'
  | 'Theme Changed'
  | 'Error Fetching Attributes'
  // unsure
  | 'Keytar Secrets Migration Failed'
  | 'Signal Action Button Clicked'
  | 'Signal Closed'
  | 'Signal Link Clicked'
  | 'Signal Opened'
  | 'Signal Shown';
