// TODO: remove
// these lists are here only for the purpose of review
// let me know if any of these are categorized wrong!

export type ConnectionScopeEvents = [
  | 'Aggregation Canceled'
  | 'Aggregation Edited'
  | 'Aggregation Executed'
  | 'Aggregation Explained'
  | 'Aggregation Export Opened'
  | 'Aggregation Exported'
  | 'Aggregation Opened'
  | 'Aggregation Saved'
  | 'Aggregation Saved As View'
  | 'Aggregation Side Panel Opened'
  | 'Aggregation Timed Out'
  | 'Aggregation Use Case Added'
  | 'Aggregation Use Case Saved'
  | 'AI Prompt Submitted'
  | 'AI Query Feedback'
  | 'AI Response Failed'
  | 'AI Response Generated'
  | 'Bulk Delete Executed'
  | 'Bulk Delete Opened'
  | 'Bulk Update Executed'
  | 'Bulk Update Favorited'
  | 'Bulk Update Opened'
  | 'Collection Created'
  | 'Connection Attempt'
  | 'Connection Failed'
  | 'CurrentOp showOperationDetails'
  | 'Database Created'
  | 'Delete Export Opened'
  | 'Delete Exported'
  | 'DetailView hideOperationDetails'
  | 'DetailView killOp'
  | 'Document Cloned'
  | 'Document Copied'
  | 'Document Deleted'
  | 'Document Inserted'
  | 'Document Updated'
  | 'Editor Type Changed'
  | 'Explain Plan Executed'
  | 'Export Completed'
  | 'Export Opened'
  | 'Query Edited'
  | 'Query Executed'
  | 'Query Export Opened'
  | 'Query Exported'
  | 'Query History Closed'
  | 'Query History Favorite Added'
  | 'Query History Favorites'
  | 'Query History Opened'
  | 'Query History Recent'
  | 'Query History Recent Used'
  | 'Query Results Refreshed'
  | 'Import Completed'
  | 'Import Error Log Opened'
  | 'Import Opened'
  | 'Index Create Opened'
  | 'Index Created'
  | 'Index Dropped'
  | 'Index Edited'
  | 'New Connection'
  | 'Performance Advisor Clicked'
  | 'Performance Paused'
  | 'Performance Resumed'
  | 'PipelineAI Feedback'
  | 'Schema Analyzed'
  | 'Schema Validation Added'
  | 'Schema Validation Edited'
  | 'Schema Validation Updated'
  | `Shell ${string}`
  | 'Switch View Type'
  | 'Update Export Opened'
  | 'Update Exported'
  | 'View Updated'
  // unsure
  | 'Focus Mode Closed'
  | 'Focus Mode Opened'
];

export type SometimesConnectionScopeEvents = [
  | 'Query History Favorite Removed' // depends! this one can be from 'my_queries' or from 'documents' screen
  | 'Query History Favorite Used' // depends! this one can be from 'my_queries' or from 'documents' screen
  | 'Screen'
];

export type GeneralScopeEvents = [
  | 'Application Launched'
  | 'Application Restart Accepted'
  | 'Atlas Link Clicked'
  | 'Atlas Sign In Error'
  | 'Atlas Sign In Success'
  | 'Atlas Sign Out'
  | 'Autoupdate Accepted'
  | 'Autoupdate Disabled'
  | 'Autoupdate Dismissed'
  | 'Autoupdate Enabled'
  | 'My Queries Filter'
  | 'My Queries Sort'
  | 'My Queries Search'
  | 'Theme Changed'
  | 'Error Fetching Attributes'
  | 'Query History Favorite Copied' // this is from 'my_queries' screen
  | 'Aggregation Deleted'
  | 'Aggregation Copied'
  | 'First Contentful Paint'
  | 'Largest Contentful Paint'
  | 'First Input Delay'
  | 'Cumulative Layout Shift'
  | 'Time to First Byte'
  | 'Guide Cue Dismissed'
  | 'Guide Cue Group Dismissed'
  // unsure
  | 'Connection Exported'
  | 'Connection Imported'
  | 'Keytar Secrets Migration Failed'
  | 'Signal Action Button Clicked'
  | 'Signal Closed'
  | 'Signal Link Clicked'
  | 'Signal Opened'
  | 'Signal Shown'
];
