/**
 * Process status constants.
 */
const PROCESS_STATUS = {
  UNSPECIFIED: 'UNSPECIFIED',
  STARTED: 'STARTED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  INTERRUPTED: 'INTERRUPTED'
};

/**
 * The finished statuses.
 */
const FINISHED_STATUSES = [
  PROCESS_STATUS.CANCELLED,
  PROCESS_STATUS.COMPLETED,
  PROCESS_STATUS.FAILED
];

export default PROCESS_STATUS;
export { FINISHED_STATUSES };
