const fs = require('fs');
const _ = require('lodash');
const yaml = require('js-yaml');
const path = require('path');

function renderTemplate(srcFile, destFile) {
  const template = fs.readFileSync(srcFile, 'utf8');
  const compile = _.template(template);
  const result = `# This file has been generated. Do not edit this file directly.
# Edit ${path.basename(srcFile)} instead.
${yaml.dump(yaml.load(compile({})))}`;

  fs.writeFileSync(destFile, result);
}

const templateFile = path.join(__dirname, 'buildvariants-and-tasks.in.yml');
const destFile = path.join(__dirname, 'buildvariants-and-tasks.yml');
renderTemplate(templateFile, destFile);
