// TODO: This is not the autogenerated file, but was aligned by augument with zlib wasm setup.
/* @ts-self-types="./snap_wasm.d.ts" */
import wasmUrl from './snap_wasm_bg.wasm';
import * as imports from './snap_wasm_bg.js';

// Load and initialize the WASM module
let initPromise = null;

async function ensureInitialized() {
  if (!initPromise) {
    initPromise = (async () => {
      const response = await fetch(wasmUrl);

      // Create the imports object that the WASM module expects
      const importsObj = {
        './snap_wasm_bg.js': imports,
      };

      const { instance } = await WebAssembly.instantiateStreaming(
        response,
        importsObj
      );
      imports.__wbg_set_wasm(instance.exports);
      instance.exports.__wbindgen_start();
    })();
  }
  await initPromise;
}

// Wrap the functions to ensure WASM is initialized before calling
export async function compress(data) {
  await ensureInitialized();
  return imports.compress(data);
}

export async function decompress(data) {
  await ensureInitialized();
  return imports.decompress(data);
}

// For compatibility, export start as an async initialization function
export async function start() {
  await ensureInitialized();
}

// Not needed for the polyfill but exported for compatibility
export async function compress_frame(data) {
  await ensureInitialized();
  return imports.compress_frame(data);
}

export async function decompress_frame(data) {
  await ensureInitialized();
  return imports.decompress_frame(data);
}
