import { expect } from 'chai';
import { exportMongodbJSONSchema } from './mongodb-json-schema';

const mixed = {
  fields: [
    {
      name: '_id',
      path: '_id',
      count: 2,
      types: [
        {
          name: 'ObjectId',
          bsonType: 'ObjectId',
          path: '_id',
          count: 2,
          values: ['62fd21136bc4507c881228f8', '62fd21136bc4507c881228f7'],
          total_count: 0,
          probability: 1,
          unique: 2,
          has_duplicates: false,
        },
      ],
      total_count: 2,
      type: 'ObjectId',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'objectOrString',
      path: 'objectOrString',
      count: 2,
      types: [
        {
          name: 'String',
          bsonType: 'String',
          path: 'objectOrString',
          count: 1,
          values: ['this is a string'],
          total_count: 0,
          probability: 0.5,
          unique: 1,
          has_duplicates: false,
        },
        {
          name: 'Document',
          bsonType: 'Document',
          path: 'objectOrString',
          count: 1,
          fields: [
            {
              name: 'thisIsAnObject',
              path: 'objectOrString.thisIsAnObject',
              count: 1,
              types: [
                {
                  name: 'Boolean',
                  bsonType: 'Boolean',
                  path: 'objectOrString.thisIsAnObject',
                  count: 1,
                  values: [true],
                  total_count: 0,
                  probability: 1,
                  unique: 1,
                  has_duplicates: false,
                },
              ],
              total_count: 1,
              type: 'Boolean',
              has_duplicates: false,
              probability: 1,
            },
          ],
          total_count: 0,
          probability: 0.5,
        },
      ],
      total_count: 2,
      type: ['String', 'Document'],
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'x',
      path: 'x',
      count: 2,
      types: [
        {
          name: 'Int32',
          bsonType: 'Int32',
          path: 'x',
          count: 1,
          values: [1],
          total_count: 0,
          probability: 0.5,
          unique: 1,
          has_duplicates: false,
        },
        {
          name: 'String',
          bsonType: 'String',
          path: 'x',
          count: 1,
          values: ['2'],
          total_count: 0,
          probability: 0.5,
          unique: 1,
          has_duplicates: false,
        },
      ],
      total_count: 2,
      type: ['Int32', 'String'],
      has_duplicates: false,
      probability: 1,
    },
  ],
  count: 2,
};

const allBsonTypes = {
  fields: [
    {
      name: '_id',
      path: '_id',
      count: 1,
      types: [
        {
          name: 'ObjectId',
          bsonType: 'ObjectId',
          path: '_id',
          count: 1,
          values: ['5d505646cf6d4fe581014ab2'],
          total_count: 0,
          probability: 1,
          unique: 1,
          has_duplicates: false,
        },
      ],
      total_count: 1,
      type: 'ObjectId',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'arrayField_canonical',
      path: 'arrayField_canonical',
      count: 1,
      types: [
        {
          name: 'Array',
          bsonType: 'Array',
          path: 'arrayField_canonical',
          count: 1,
          types: [
            {
              name: 'String',
              bsonType: 'String',
              path: 'arrayField_canonical',
              count: 2,
              values: [
                "import React, {\n  useCallback,\n  useEffect,\n  useMemo,\n  useRef,\n  useState,\n} from 'react';\nimport { css, cx } from '@leafygreen-ui/emotion';\nimport { uiColors } from '@leafygreen-ui/palette';\nimport type {\n  default as HadronDocumentType,\n  Element as HadronElementType,\n  Editor as EditorType,\n} from 'hadron-document';\nimport { ElementEvents, ElementEditor } from 'hadron-document';\nimport BSONValue from '../bson-value';\nimport { fontFamilies, spacing } from '@leafygreen-ui/tokens';\nimport { KeyEditor, ValueEditor, TypeEditor } from './element-editors';\nimport { EditActions, AddFieldActions } from './element-actions';\nimport { FontAwesomeIcon } from './font-awesome-icon';\nimport { useAutoFocusContext, AutoFocusContext } from './auto-focus-context';\n\nfunction useForceUpdate() {\n  const [, setState] = useState({});\n  const forceUpdate = useCallback(() => {\n    setState({});\n  }, []);\n  return forceUpdate;\n}\n\nfunction getEditorByType(type: HadronElementType['type']) {\n  switch (type) {\n    case 'Date':\n    case 'String':\n    case 'Decimal128':\n    case 'Double':\n    case 'Int32':\n    case 'Int64':\n    case 'Null':\n    case 'Undefined':\n    case 'ObjectId':\n      return ElementEditor[`${type}Editor` as const];\n    default:\n      return ElementEditor.StandardEditor;\n  }\n}\n\nfunction useElementEditor(el: HadronElementType) {\n  const editor = useRef<EditorType | null>(null);\n\n  if (!editor.current) {\n    const Editor = getEditorByType(el.currentType);\n    editor.current = new Editor(el);\n  }\n\n  useEffect(() => {\n    if (\n      editor.current?.element.uuid !== el.uuid ||\n      editor.current?.element.currentType !== el.currentType\n    ) {\n      const Editor = getEditorByType(el.currentType);\n      editor.current = new Editor(el);\n    }\n  }, [el, el.uuid, el.currentType]);\n\n  return editor.current;\n}\n\nfunction useHadronElement(el: HadronElementType) {\n  const forceUpdate = useForceUpdate();\n  const editor = useElementEditor(el);\n  // NB: Duplicate key state is kept local to the component and not derived on\n  // every change so that only the changed key is highlighed as duplicate\n  const [isDuplicateKey, setIsDuplicateKey] = useState(() => {\n    return el.isDuplicateKey(el.currentKey);\n  });\n\n  const onElementChanged = useCallback(\n    (changedElement: HadronElementType) => {\n      if (el.uuid === changedElement.uuid) {\n        forceUpdate();\n      }\n    },\n    [el, forceUpdate]\n  );\n\n  const onElementAddedOrRemoved = useCallback(\n    (\n      _el: HadronElementType,\n      parentEl: HadronElementType | HadronDocumentType | null\n    ) => {\n      if (el === parentEl) {\n        forceUpdate();\n      }\n    },\n    [el, forceUpdate]\n  );\n\n  useEffect(() => {\n    el.on(ElementEvents.Converted, onElementChanged);\n    el.on(ElementEvents.Edited, onElementChanged);\n    el.on(ElementEvents.Reverted, onElementChanged);\n    el.on(ElementEvents.Invalid, onElementChanged);\n    el.on(ElementEvents.Valid, onElementChanged);\n    el.on(ElementEvents.Added, onElementAddedOrRemoved);\n    el.on(ElementEvents.Removed, onElementAddedOrRemoved);\n\n    return () => {\n      el.off(ElementEvents.Converted, onElementChanged);\n      el.off(ElementEvents.Edited, onElementChanged);\n      el.off(ElementEvents.Reverted, onElementChanged);\n      el.off(ElementEvents.Valid, onElementChanged);\n      el.off(ElementEvents.Added, onElementAddedOrRemoved);\n      el.off(ElementEvents.Removed, onElementAddedOrRemoved);\n    };\n  }, [el, onElementChanged, onElementAddedOrRemoved]);\n\n  const isValid = el.isCurrentTypeValid();\n\n  return {\n    id: el.uuid,\n    key: {\n      value: el.currentKey,\n      change(newVal: string) {\n        setIsDuplicateKey(el.isDuplicateKey(newVal));\n        el.rename(newVal);\n      },\n      // TODO: isKeyEditable should probably account for Array parents on it's\n      // own, but right now `isValueEditable` has a weird dependency on it and\n      // so marking aray keys uneditable breaks value editing\n      editable: el.isKeyEditable() && el.parent?.currentType !== 'Array',\n      valid: !isDuplicateKey,\n      validationMessage: isDuplicateKey\n        ? `Duplicate key \"${el.currentKey}\" - this will overwrite previous values`\n        : null,\n    },\n    value: {\n      value: editor.value(),\n      originalValue: el.currentValue,\n      change(newVal: string) {\n        editor.edit(newVal);\n      },\n      editable:\n        el.isValueEditable() &&\n        el.currentType !== 'Object' &&\n        el.currentType !== 'Array',\n      valid: isValid,\n      validationMessage: !isValid ? el.invalidTypeMessage ?? null : null,\n    },\n    type: {\n      value: el.currentType,\n      change(newVal: HadronElementType['type']) {\n        el.changeType(newVal);\n      },\n    },\n    revert: el.isRevertable() ? el.revert.bind(el) : null,\n    remove: el.isNotActionable() ? null : el.remove.bind(el),\n    expandable: Boolean(el.elements),\n    children: el.elements ? [...el.elements] : [],\n    level: el.level,\n    parentType: el.parent?.currentType,\n    removed: el.isRemoved(),\n  };\n}\n\nconst buttonReset = css({\n  margin: 0,\n  padding: 0,\n  border: 'none',\n  background: 'none',\n});\n\nconst hadronElement = css({\n  display: 'flex',\n  paddingLeft: spacing[2],\n  paddingRight: spacing[2],\n  '&:hover': {\n    backgroundColor: uiColors.gray.light2,\n  },\n});\n\nconst elementInvalid = css({\n  backgroundColor: uiColors.yellow.light3,\n  '&:hover': {\n    backgroundColor: uiColors.yellow.light2,\n  },\n});\n\nconst elementRemoved = css({\n  backgroundColor: uiColors.red.light3,\n  '&:hover': {\n    backgroundColor: uiColors.red.light2,\n  },\n});\n\nconst elementActions = css({\n  flex: 'none',\n  width: spacing[3],\n});\n\nconst elementLineNumber = css({\n  flex: 'none',\n  position: 'relative',\n  marginLeft: spacing[1],\n  boxSizing: 'content-box',\n});\n\nconst addFieldActionsContainer = css({\n  position: 'absolute',\n  top: 0,\n  right: 0,\n});\n\nconst lineNumberCount = css({\n  '&::before': {\n    display: 'block',\n    width: '100%',\n    counterIncrement: 'line-number',\n    content: 'counter(line-number)',\n    textAlign: 'end',\n    color: uiColors.gray.base,\n  },\n});\n\nconst lineNumberInvalid = css({\n  backgroundColor: uiColors.yellow.base,\n  '&::before': {\n    color: uiColors.yellow.dark2,\n  },\n});\n\nconst lineNumberRemoved = css({\n  backgroundColor: uiColors.red.base,\n  color: uiColors.red.light3,\n  '&::before': {\n    color: uiColors.red.light3,\n  },\n});\n\nconst elementSpacer = css({\n  flex: 'none',\n});\n\nconst elementExpand = css({\n  width: spacing[3],\n  flex: 'none',\n});\n\nconst elementKey = css({\n  flex: 'none',\n  fontWeight: 'bold',\n  maxWidth: '70%',\n  // textOverflow: 'ellipsis',\n});\n\nconst elementDivider = css({\n  flex: 'none',\n  userSelect: 'none',\n});\n\nconst elementValue = css({\n  flex: 1,\n  minWidth: 0,\n  maxWidth: '100%',\n});\n\nconst elementType = css({\n  flex: 'none',\n});\n\nconst actions = css({\n  display: 'none',\n});\n\nconst actionsVisible = css({\n  // We are deliberately not using useFocus and useHover hooks in the component\n  // as these listeners are expensive and so with the amount of code and DOM on\n  // the screen causes noticeable frame skips in the browser. This code is a bit\n  // brittle as we can't really reference the exact className of an emotion\n  // style so we have to rely on data attributes, but the chances that this\n  // should ever be an issue are pretty slim\n  '[data-document-element=\"true\"]:hover &, [data-document-element=\"true\"]:focus-within &':\n    {\n      display: 'block',\n    },\n});\n\nconst lineNumberCountHidden = css({\n  // See above\n  '[data-document-element=\"true\"]:hover &::before, [data-document-element=\"true\"]:focus-within &::before':\n    {\n      visibility: 'hidden',\n    },\n});\n\nconst HadronElement: React.FunctionComponent<{\n  value: HadronElementType;\n  editingEnabled: boolean;\n  onEditStart?: (id: string, field: 'key' | 'value') => void;\n  allExpanded: boolean;\n  lineNumberSize: number;\n  onAddElement(el: HadronElementType): void;\n}> = ({\n  value: element,\n  editingEnabled,\n  onEditStart,\n  allExpanded,\n  lineNumberSize,\n  onAddElement,\n}) => {\n  const autoFocus = useAutoFocusContext();\n  const [expanded, setExpanded] = useState(allExpanded);\n  const {\n    id,\n    key,\n    value,\n    type,\n    revert,\n    remove,\n    expandable,\n    children,\n    level,\n    parentType,\n    removed,\n  } = useHadronElement(element);\n\n  useEffect(() => {\n    setExpanded(allExpanded);\n  }, [allExpanded]);\n\n  const toggleExpanded = useCallback(() => {\n    setExpanded((val) => !val);\n  }, []);\n\n  const lineNumberMinWidth = useMemo(() => {\n    // Only account for ~ line count length if we are in editing mode\n    if (editingEnabled) {\n      const charCount = String(lineNumberSize).length;\n      return charCount > 2 ? `${charCount}.5ch` : spacing[3];\n    }\n    return spacing[3];\n  }, [lineNumberSize, editingEnabled]);\n\n  const onLineClick = useCallback(() => {\n    toggleExpanded();\n  }, [toggleExpanded]);\n\n  const isValid = key.valid && value.valid;\n  const shouldShowActions = editingEnabled;\n\n  const elementProps = {\n    className: cx(\n      hadronElement,\n      removed ? elementRemoved : editingEnabled && !isValid && elementInvalid\n    ),\n    onClick() {\n      onLineClick();\n    },\n  };\n\n  return (\n    <>\n      <div data-document-element=\"true\" {...elementProps}>\n        <div className={elementActions}>\n          <div className={cx(actions, shouldShowActions && actionsVisible)}>\n            <EditActions\n              onRevert={revert}\n              onRemove={remove}\n              editing={editingEnabled}\n            ></EditActions>\n          </div>\n        </div>\n        <div\n          className={cx(\n            elementLineNumber,\n            editingEnabled && lineNumberCount,\n            shouldShowActions && lineNumberCountHidden,\n            removed\n              ? lineNumberRemoved\n              : editingEnabled && !isValid && lineNumberInvalid\n          )}\n          style={{ minWidth: lineNumberMinWidth }}\n        >\n          <div\n            className={cx(\n              actions,\n              addF",
                'The standard Lorem Ipsum passage, used since the 1500s\n\n"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."\nSection 1.10.32 of "de Finibus Bonorum et Malorum", written by Cicero in 45 BC\n\n"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?"\n1914 translation by H. Rackham\n\n"But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness. No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful. Nor again is there anyone who loves or pursues or desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure. To take a trivial example, which of us ever undertakes laborious physical exercise, except to obtain some advantage from it? But who has any right to find fault with a man who chooses to enjoy a pleasure that has no annoying consequences, or one who avoids a pain that produces no resultant pleasure?"\nSection 1.10.33 of "de Finibus Bonorum et Malorum", written by Cicero in 45 BC\n\n"At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat."\n1914 translation by H. Rackham\n\n"On the other hand, we denounce with righteous indignation and dislike men who are so beguiled and demoralized by the charms of pleasure of the moment, so blinded by desire, that they cannot foresee the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking from toil and pain. These cases are perfectly simple and easy to distinguish. In a free hour, when our power of choice is untrammelled and when nothing prevents our being able to do what we like best, every pleasure is to be welcomed and every pain avoided. But in certain circumstances and owing to the claims of duty or the obligations of business it will frequently occur that pleasures have to be repudiated and annoyances accepted. The wise man therefore always holds in these matters to this principle of selection: he rejects pleasures to secure other greater pleasures, or else he endures pains to avoid worse pains."\n',
              ],
              total_count: 0,
              probability: 1,
              unique: 2,
              has_duplicates: false,
            },
          ],
          lengths: [2],
          total_count: 2,
          probability: 1,
          average_length: 2,
        },
      ],
      total_count: 1,
      type: 'Array',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'arrayField_relaxed',
      path: 'arrayField_relaxed',
      count: 1,
      types: [
        {
          name: 'Array',
          bsonType: 'Array',
          path: 'arrayField_relaxed',
          count: 1,
          types: [
            {
              name: 'String',
              bsonType: 'String',
              path: 'arrayField_relaxed',
              count: 1,
              values: ['hello'],
              total_count: 0,
              probability: 0.5,
              unique: 1,
              has_duplicates: false,
            },
            {
              name: 'Int32',
              bsonType: 'Int32',
              path: 'arrayField_relaxed',
              count: 1,
              values: [10],
              total_count: 0,
              probability: 0.5,
              unique: 1,
              has_duplicates: false,
            },
          ],
          lengths: [2],
          total_count: 2,
          probability: 1,
          average_length: 2,
        },
      ],
      total_count: 1,
      type: 'Array',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'big_array',
      path: 'big_array',
      count: 1,
      types: [
        {
          name: 'Array',
          bsonType: 'Array',
          path: 'big_array',
          count: 1,
          types: [
            {
              name: 'Int32',
              bsonType: 'Int32',
              path: 'big_array',
              count: 99,
              values: [
                1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
              ],
              total_count: 0,
              probability: 1,
              unique: 1,
              has_duplicates: true,
            },
          ],
          lengths: [99],
          total_count: 99,
          probability: 1,
          average_length: 99,
        },
      ],
      total_count: 1,
      type: 'Array',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'big_array1',
      path: 'big_array1',
      count: 1,
      types: [
        {
          name: 'Array',
          bsonType: 'Array',
          path: 'big_array1',
          count: 1,
          types: [
            {
              name: 'Int32',
              bsonType: 'Int32',
              path: 'big_array1',
              count: 3,
              values: [1, 2, 3],
              total_count: 0,
              probability: 1,
              unique: 3,
              has_duplicates: false,
            },
          ],
          lengths: [3],
          total_count: 3,
          probability: 1,
          average_length: 3,
        },
      ],
      total_count: 1,
      type: 'Array',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'bin1',
      path: 'bin1',
      count: 1,
      types: [
        {
          name: 'Binary',
          bsonType: 'Binary',
          path: 'bin1',
          count: 1,
          values: [''],
          total_count: 0,
          probability: 1,
          unique: 1,
          has_duplicates: false,
        },
      ],
      total_count: 1,
      type: 'Binary',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'bla',
      path: 'bla',
      count: 1,
      types: [
        {
          name: 'Int32',
          bsonType: 'Int32',
          path: 'bla',
          count: 1,
          values: [1],
          total_count: 0,
          probability: 1,
          unique: 1,
          has_duplicates: false,
        },
      ],
      total_count: 1,
      type: 'Int32',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'blabla',
      path: 'blabla',
      count: 1,
      types: [
        {
          name: 'Int32',
          bsonType: 'Int32',
          path: 'blabla',
          count: 1,
          values: [1],
          total_count: 0,
          probability: 1,
          unique: 1,
          has_duplicates: false,
        },
      ],
      total_count: 1,
      type: 'Int32',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'blablabla',
      path: 'blablabla',
      count: 1,
      types: [
        {
          name: 'String',
          bsonType: 'String',
          path: 'blablabla',
          count: 1,
          values: ['1'],
          total_count: 0,
          probability: 1,
          unique: 1,
          has_duplicates: false,
        },
      ],
      total_count: 1,
      type: 'String',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'bson_map',
      path: 'bson_map',
      count: 1,
      types: [
        {
          name: 'Document',
          bsonType: 'Document',
          path: 'bson_map',
          count: 1,
          fields: [
            {
              name: 'one',
              path: 'bson_map.one',
              count: 1,
              types: [
                {
                  name: 'Int32',
                  bsonType: 'Int32',
                  path: 'bson_map.one',
                  count: 1,
                  values: [1],
                  total_count: 0,
                  probability: 1,
                  unique: 1,
                  has_duplicates: false,
                },
              ],
              total_count: 1,
              type: 'Int32',
              has_duplicates: false,
              probability: 1,
            },
            {
              name: 'two',
              path: 'bson_map.two',
              count: 1,
              types: [
                {
                  name: 'Int32',
                  bsonType: 'Int32',
                  path: 'bson_map.two',
                  count: 1,
                  values: [2],
                  total_count: 0,
                  probability: 1,
                  unique: 1,
                  has_duplicates: false,
                },
              ],
              total_count: 1,
              type: 'Int32',
              has_duplicates: false,
              probability: 1,
            },
          ],
          total_count: 0,
          probability: 1,
        },
      ],
      total_count: 1,
      type: 'Document',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'bsonmap',
      path: 'bsonmap',
      count: 1,
      types: [
        {
          name: 'Document',
          bsonType: 'Document',
          path: 'bsonmap',
          count: 1,
          fields: [],
          total_count: 0,
          probability: 1,
        },
      ],
      total_count: 1,
      type: 'Document',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'code',
      path: 'code',
      count: 1,
      types: [
        {
          name: 'Code',
          bsonType: 'Code',
          path: 'code',
          count: 1,
          values: [
            {
              code: 'var a = 1',
              scope: {
                foo: 2,
              },
            },
          ],
          total_count: 0,
          probability: 1,
          unique: 1,
          has_duplicates: false,
        },
      ],
      total_count: 1,
      type: 'Code',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'dateBefore1970',
      path: 'dateBefore1970',
      count: 1,
      types: [
        {
          name: 'Date',
          bsonType: 'Date',
          path: 'dateBefore1970',
          count: 1,
          values: ['1920-01-01T00:00:00.000Z'],
          total_count: 0,
          probability: 1,
          unique: 1,
          has_duplicates: false,
        },
      ],
      total_count: 1,
      type: 'Date',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'dateField_canonical',
      path: 'dateField_canonical',
      count: 1,
      types: [
        {
          name: 'Date',
          bsonType: 'Date',
          path: 'dateField_canonical',
          count: 1,
          values: ['2020-09-11T17:44:14.692Z'],
          total_count: 0,
          probability: 1,
          unique: 1,
          has_duplicates: false,
        },
      ],
      total_count: 1,
      type: 'Date',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'dateField_relaxed',
      path: 'dateField_relaxed',
      count: 1,
      types: [
        {
          name: 'Date',
          bsonType: 'Date',
          path: 'dateField_relaxed',
          count: 1,
          values: ['1019-08-11T17:54:16.692Z'],
          total_count: 0,
          probability: 1,
          unique: 1,
          has_duplicates: false,
        },
      ],
      total_count: 1,
      type: 'Date',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'dbl',
      path: 'dbl',
      count: 1,
      types: [
        {
          name: 'Int32',
          bsonType: 'Int32',
          path: 'dbl',
          count: 1,
          values: [1],
          total_count: 0,
          probability: 1,
          unique: 1,
          has_duplicates: false,
        },
      ],
      total_count: 1,
      type: 'Int32',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'dbref1',
      path: 'dbref1',
      count: 1,
      types: [
        {
          name: 'DBRef',
          bsonType: 'DBRef',
          path: 'dbref1',
          count: 1,
          values: [
            {
              $ref: 'foo',
              $id: 'bar',
            },
          ],
          total_count: 0,
          probability: 1,
          unique: 1,
          has_duplicates: false,
        },
      ],
      total_count: 1,
      type: 'DBRef',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'decimal128Field',
      path: 'decimal128Field',
      count: 1,
      types: [
        {
          name: 'Decimal128',
          bsonType: 'Decimal128',
          path: 'decimal128Field',
          count: 1,
          values: [
            {
              $numberDecimal: '10.99',
            },
          ],
          total_count: 0,
          probability: 1,
          unique: 1,
          has_duplicates: false,
        },
      ],
      total_count: 1,
      type: 'Decimal128',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'documentField',
      path: 'documentField',
      count: 1,
      types: [
        {
          name: 'Document',
          bsonType: 'Document',
          path: 'documentField',
          count: 1,
          fields: [
            {
              name: 'a',
              path: 'documentField.a',
              count: 1,
              types: [
                {
                  name: 'String',
                  bsonType: 'String',
                  path: 'documentField.a',
                  count: 1,
                  values: ['hello'],
                  total_count: 0,
                  probability: 1,
                  unique: 1,
                  has_duplicates: false,
                },
              ],
              total_count: 1,
              type: 'String',
              has_duplicates: false,
              probability: 1,
            },
          ],
          total_count: 0,
          probability: 1,
        },
      ],
      total_count: 1,
      type: 'Document',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'doubleField_canonical',
      path: 'doubleField_canonical',
      count: 1,
      types: [
        {
          name: 'Double',
          bsonType: 'Double',
          path: 'doubleField_canonical',
          count: 1,
          values: [10.5],
          total_count: 0,
          probability: 1,
          unique: 1,
          has_duplicates: false,
        },
      ],
      total_count: 1,
      type: 'Double',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'doubleField_relaxed',
      path: 'doubleField_relaxed',
      count: 1,
      types: [
        {
          name: 'Double',
          bsonType: 'Double',
          path: 'doubleField_relaxed',
          count: 1,
          values: [10.5],
          total_count: 0,
          probability: 1,
          unique: 1,
          has_duplicates: false,
        },
      ],
      total_count: 1,
      type: 'Double',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'foo',
      path: 'foo',
      count: 1,
      types: [
        {
          name: 'Document',
          bsonType: 'Document',
          path: 'foo',
          count: 1,
          fields: [
            {
              name: 'bar',
              path: 'foo.bar',
              count: 1,
              types: [
                {
                  name: 'Document',
                  bsonType: 'Document',
                  path: 'foo.bar',
                  count: 1,
                  fields: [
                    {
                      name: 'buz',
                      path: 'foo.bar.buz',
                      count: 1,
                      types: [
                        {
                          name: 'Document',
                          bsonType: 'Document',
                          path: 'foo.bar.buz',
                          count: 1,
                          fields: [
                            {
                              name: 'bla',
                              path: 'foo.bar.buz.bla',
                              count: 1,
                              types: [
                                {
                                  name: 'Document',
                                  bsonType: 'Document',
                                  path: 'foo.bar.buz.bla',
                                  count: 1,
                                  fields: [
                                    {
                                      name: 'lol',
                                      path: 'foo.bar.buz.bla.lol',
                                      count: 1,
                                      types: [
                                        {
                                          name: 'Int32',
                                          bsonType: 'Int32',
                                          path: 'foo.bar.buz.bla.lol',
                                          count: 1,
                                          values: [1],
                                          total_count: 0,
                                          probability: 1,
                                          unique: 1,
                                          has_duplicates: false,
                                        },
                                      ],
                                      total_count: 1,
                                      type: 'Int32',
                                      has_duplicates: false,
                                      probability: 1,
                                    },
                                  ],
                                  total_count: 0,
                                  probability: 1,
                                },
                              ],
                              total_count: 1,
                              type: 'Document',
                              has_duplicates: false,
                              probability: 1,
                            },
                          ],
                          total_count: 0,
                          probability: 1,
                        },
                      ],
                      total_count: 1,
                      type: 'Document',
                      has_duplicates: false,
                      probability: 1,
                    },
                  ],
                  total_count: 0,
                  probability: 1,
                },
              ],
              total_count: 1,
              type: 'Document',
              has_duplicates: false,
              probability: 1,
            },
          ],
          total_count: 0,
          probability: 1,
        },
      ],
      total_count: 1,
      type: 'Document',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'infiniteNumber',
      path: 'infiniteNumber',
      count: 1,
      types: [
        {
          name: 'Null',
          bsonType: 'Null',
          path: 'infiniteNumber',
          count: 1,
          total_count: 0,
          probability: 1,
          unique: 1,
          has_duplicates: false,
        },
      ],
      total_count: 1,
      type: 'Null',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'int32field_canonical',
      path: 'int32field_canonical',
      count: 1,
      types: [
        {
          name: 'Int32',
          bsonType: 'Int32',
          path: 'int32field_canonical',
          count: 1,
          values: [10],
          total_count: 0,
          probability: 1,
          unique: 1,
          has_duplicates: false,
        },
      ],
      total_count: 1,
      type: 'Int32',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'int32field_relaxed',
      path: 'int32field_relaxed',
      count: 1,
      types: [
        {
          name: 'Int32',
          bsonType: 'Int32',
          path: 'int32field_relaxed',
          count: 1,
          values: [10],
          total_count: 0,
          probability: 1,
          unique: 1,
          has_duplicates: false,
        },
      ],
      total_count: 1,
      type: 'Int32',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'int64_number',
      path: 'int64_number',
      count: 1,
      types: [
        {
          name: 'Long',
          bsonType: 'Long',
          path: 'int64_number',
          count: 1,
          values: [
            {
              low: 1404961089,
              high: 1932494342,
              unsigned: false,
            },
          ],
          total_count: 0,
          probability: 1,
          unique: 1,
          has_duplicates: false,
        },
      ],
      total_count: 1,
      type: 'Long',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'int64Field_canonical',
      path: 'int64Field_canonical',
      count: 1,
      types: [
        {
          name: 'Int32',
          bsonType: 'Int32',
          path: 'int64Field_canonical',
          count: 1,
          values: [50],
          total_count: 0,
          probability: 1,
          unique: 1,
          has_duplicates: false,
        },
      ],
      total_count: 1,
      type: 'Int32',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'int64Field_gt_MAX_SAFE_INTEGER',
      path: 'int64Field_gt_MAX_SAFE_INTEGER',
      count: 1,
      types: [
        {
          name: 'Long',
          bsonType: 'Long',
          path: 'int64Field_gt_MAX_SAFE_INTEGER',
          count: 1,
          values: [
            {
              low: -1,
              high: 20971519,
              unsigned: false,
            },
          ],
          total_count: 0,
          probability: 1,
          unique: 1,
          has_duplicates: false,
        },
      ],
      total_count: 1,
      type: 'Long',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'int64Field_relaxed',
      path: 'int64Field_relaxed',
      count: 1,
      types: [
        {
          name: 'Int32',
          bsonType: 'Int32',
          path: 'int64Field_relaxed',
          count: 1,
          values: [50],
          total_count: 0,
          probability: 1,
          unique: 1,
          has_duplicates: false,
        },
      ],
      total_count: 1,
      type: 'Int32',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'maxKeyField',
      path: 'maxKeyField',
      count: 1,
      types: [
        {
          name: 'MaxKey',
          bsonType: 'MaxKey',
          path: 'maxKeyField',
          count: 1,
          values: [{}],
          total_count: 0,
          probability: 1,
          unique: 1,
          has_duplicates: false,
        },
      ],
      total_count: 1,
      type: 'MaxKey',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'minKeyField',
      path: 'minKeyField',
      count: 1,
      types: [
        {
          name: 'MinKey',
          bsonType: 'MinKey',
          path: 'minKeyField',
          count: 1,
          values: [{}],
          total_count: 0,
          probability: 1,
          unique: 1,
          has_duplicates: false,
        },
      ],
      total_count: 1,
      type: 'MinKey',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'nullField',
      path: 'nullField',
      count: 1,
      types: [
        {
          name: 'Null',
          bsonType: 'Null',
          path: 'nullField',
          count: 1,
          total_count: 0,
          probability: 1,
          unique: 1,
          has_duplicates: false,
        },
      ],
      total_count: 1,
      type: 'Null',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'regex',
      path: 'regex',
      count: 1,
      types: [
        {
          name: 'RegExp',
          bsonType: 'RegExp',
          path: 'regex',
          count: 1,
          values: [{}],
          total_count: 0,
          probability: 1,
          unique: 1,
          has_duplicates: false,
        },
      ],
      total_count: 1,
      type: 'RegExp',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'regex2',
      path: 'regex2',
      count: 1,
      types: [
        {
          name: 'RegExp',
          bsonType: 'RegExp',
          path: 'regex2',
          count: 1,
          values: [{}],
          total_count: 0,
          probability: 1,
          unique: 1,
          has_duplicates: false,
        },
      ],
      total_count: 1,
      type: 'RegExp',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'regex3',
      path: 'regex3',
      count: 1,
      types: [
        {
          name: 'RegExp',
          bsonType: 'RegExp',
          path: 'regex3',
          count: 1,
          values: [{}],
          total_count: 0,
          probability: 1,
          unique: 1,
          has_duplicates: false,
        },
      ],
      total_count: 1,
      type: 'RegExp',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'regex_once_more',
      path: 'regex_once_more',
      count: 1,
      types: [
        {
          name: 'RegExp',
          bsonType: 'RegExp',
          path: 'regex_once_more',
          count: 1,
          values: [{}],
          total_count: 0,
          probability: 1,
          unique: 1,
          has_duplicates: false,
        },
      ],
      total_count: 1,
      type: 'RegExp',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'regexField',
      path: 'regexField',
      count: 1,
      types: [
        {
          name: 'RegExp',
          bsonType: 'RegExp',
          path: 'regexField',
          count: 1,
          values: [{}],
          total_count: 0,
          probability: 1,
          unique: 1,
          has_duplicates: false,
        },
      ],
      total_count: 1,
      type: 'RegExp',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'smbl',
      path: 'smbl',
      count: 1,
      types: [
        {
          name: 'BSONSymbol',
          bsonType: 'BSONSymbol',
          path: 'smbl',
          count: 1,
          values: ['abcd'],
          total_count: 0,
          probability: 1,
          unique: 1,
          has_duplicates: false,
        },
      ],
      total_count: 1,
      type: 'BSONSymbol',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'symbol',
      path: 'symbol',
      count: 1,
      types: [
        {
          name: 'BSONSymbol',
          bsonType: 'BSONSymbol',
          path: 'symbol',
          count: 1,
          values: ['bar'],
          total_count: 0,
          probability: 1,
          unique: 1,
          has_duplicates: false,
        },
      ],
      total_count: 1,
      type: 'BSONSymbol',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'timestampField',
      path: 'timestampField',
      count: 1,
      types: [
        {
          name: 'Timestamp',
          bsonType: 'Timestamp',
          path: 'timestampField',
          count: 1,
          values: [
            {
              $timestamp: '5860512960',
            },
          ],
          total_count: 0,
          probability: 1,
          unique: 1,
          has_duplicates: false,
        },
      ],
      total_count: 1,
      type: 'Timestamp',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'uuid',
      path: 'uuid',
      count: 1,
      types: [
        {
          name: 'Binary',
          bsonType: 'Binary',
          path: 'uuid',
          count: 1,
          values: ['63b985b8-e8dd-4bda-9087-e4402f1a3ff5'],
          total_count: 0,
          probability: 1,
          unique: 1,
          has_duplicates: false,
        },
      ],
      total_count: 1,
      type: 'Binary',
      has_duplicates: false,
      probability: 1,
    },
    {
      name: 'veryLongKey',
      path: 'veryLongKey',
      count: 1,
      types: [
        {
          name: 'String',
          bsonType: 'String',
          path: 'veryLongKey',
          count: 1,
          values: ['veryLongKey'],
          total_count: 0,
          probability: 1,
          unique: 1,
          has_duplicates: false,
        },
      ],
      total_count: 1,
      type: 'String',
      has_duplicates: false,
      probability: 1,
    },
  ],
  count: 1,
};

describe('convertToJSONSchema', function () {
  it('converts all bson types to json schema', function () {
    const converted = exportMongodbJSONSchema(allBsonTypes as any, {
      requireMandatoryProperties: false,
      includeId: false,
    });
    expect(converted).to.deep.equal({
      properties: {
        _id: { bsonType: 'objectId' },
        arrayField_canonical: {
          bsonType: 'array',
          items: { bsonType: 'string' },
        },
        arrayField_relaxed: {
          bsonType: 'array',
          items: { bsonType: 'string' },
        },
        big_array: { bsonType: 'array', items: { bsonType: 'int' } },
        big_array1: { bsonType: 'array', items: { bsonType: 'int' } },
        bin1: { bsonType: 'binData' },
        bla: { bsonType: 'int' },
        blabla: { bsonType: 'int' },
        blablabla: { bsonType: 'string' },
        bson_map: {
          bsonType: 'object',
          properties: { one: { bsonType: 'int' }, two: { bsonType: 'int' } },
        },
        bsonmap: { bsonType: 'object', properties: {} },
        code: { bsonType: 'javascriptWithScope' },
        dateBefore1970: { bsonType: 'date' },
        dateField_canonical: { bsonType: 'date' },
        dateField_relaxed: { bsonType: 'date' },
        dbl: { bsonType: 'int' },
        dbref1: { bsonType: 'dbPointer' },
        decimal128Field: { bsonType: 'decimal' },
        documentField: {
          bsonType: 'object',
          properties: { a: { bsonType: 'string' } },
        },
        doubleField_canonical: { bsonType: 'double' },
        doubleField_relaxed: { bsonType: 'double' },
        foo: {
          bsonType: 'object',
          properties: {
            bar: {
              bsonType: 'object',
              properties: {
                buz: {
                  bsonType: 'object',
                  properties: {
                    bla: {
                      bsonType: 'object',
                      properties: { lol: { bsonType: 'int' } },
                    },
                  },
                },
              },
            },
          },
        },
        infiniteNumber: { bsonType: 'null' },
        int32field_canonical: { bsonType: 'int' },
        int32field_relaxed: { bsonType: 'int' },
        int64_number: { bsonType: 'long' },
        int64Field_canonical: { bsonType: 'int' },
        int64Field_gt_MAX_SAFE_INTEGER: { bsonType: 'long' },
        int64Field_relaxed: { bsonType: 'int' },
        maxKeyField: { bsonType: 'maxKey' },
        minKeyField: { bsonType: 'minKey' },
        nullField: { bsonType: 'null' },
        regex: { bsonType: 'regex', pattern: {} },
        regex2: { bsonType: 'regex', pattern: {} },
        regex3: { bsonType: 'regex', pattern: {} },
        regex_once_more: { bsonType: 'regex', pattern: {} },
        regexField: { bsonType: 'regex', pattern: {} },
        smbl: { bsonType: 'symbol' },
        symbol: { bsonType: 'symbol' },
        timestampField: { bsonType: 'timestamp' },
        uuid: { bsonType: 'binData' },
        veryLongKey: { bsonType: 'string' },
      },
    });
  });

  it('converts mixed types to json schema', function () {
    const converted = exportMongodbJSONSchema(mixed as any, {
      requireMandatoryProperties: false,
      includeId: false,
    });
    expect(converted).to.deep.equal({
      properties: {
        _id: { bsonType: 'objectId' },
        objectOrString: {
          anyOf: [
            { bsonType: 'string' },
            {
              bsonType: 'object',
              properties: { thisIsAnObject: { bsonType: 'bool' } },
            },
          ],
        },
        x: { bsonType: ['int', 'string'] },
      },
    });
  });
});
