const Reflux = require('reflux');

const Actions = Reflux.createActions({
  parseConnectionString: { sync: true },
  resetConnection: { sync: true },
  onAuthSourceChanged: { sync: true },
  onAuthStrategyChanged: { sync: true },
  onChangeViewClicked: { sync: true },
  onConnectionFormChanged: { sync: true },
  onConnectionSelected: { sync: true },
  onConnect: { sync: true },
  onCreateFavorite: { sync: true },
  onCreateRecent: { sync: true },
  onCustomUrlChanged: { sync: true },
  onDeleteConnection: { sync: true },
  onDeleteConnections: { sync: true },
  onDisconnect: { sync: true },
  onExternalLinkClicked: { sync: true },
  onFavoriteNameChanged: { sync: true },
  onFavoriteSelected: { sync: true },
  onHostnameChanged: { sync: true },
  onPasswordChanged: { sync: true },
  onPortChanged: { sync: true },
  onReadPreferenceChanged: { sync: true },
  onReplicaSetChanged: { sync: true },
  onSaveConnection: { sync: true },
  onSSLCAChanged: { sync: true },
  onSSLCertificateChanged: { sync: true },
  onSSLMethodChanged: { sync: true },
  onSSLPrivateKeyChanged: { sync: true },
  onSSLPrivateKeyPasswordChanged: { sync: true },
  onSSHTunnelPasswordChanged: { sync: true },
  onSSHTunnelPassphraseChanged: { sync: true },
  onSSHTunnelHostnameChanged: { sync: true },
  onSSHTunnelUsernameChanged: { sync: true },
  onSSHTunnelPortChanged: { sync: true },
  onSSHTunnelIdentityFileChanged: { sync: true },
  onSSHTunnelChanged: { sync: true },
  onSRVRecordToggle: { sync: true },
  onUsernameChanged: { sync: true }
});

module.exports = Actions;
