import { readFileSync, writeFileSync } from 'node:fs';
import openapiTS, { astToString } from 'openapi-typescript';
import { ATLAS_ADMIN_API_DEFAULT_VERSION } from '../src/version.ts';

// Customer FOAS: every stable resource version of every operation, no internal-only content.
const DEFAULT_SPEC =
  'https://raw.githubusercontent.com/mongodb/openapi/main/openapi/v2.json';
const VERSIONED_JSON = /^application\/vnd\.atlas\.(\d{4}-\d{2}-\d{2})\+json$/;
const METHODS = ['get', 'post', 'put', 'patch', 'delete'] as const;

type Operation = {
  operationId?: string;
  responses?: Record<string, { content?: Record<string, unknown> }>;
};
type Spec = {
  paths: Record<string, Partial<Record<(typeof METHODS)[number], Operation>>>;
};

const specArg = process.argv.indexOf('--spec');
const specSource =
  specArg !== -1
    ? process.argv[specArg + 1]
    : process.env.ATLAS_OPENAPI_SPEC ?? DEFAULT_SPEC;
if (!specSource) throw new Error('--spec requires a path or URL');

const specText = /^https?:\/\//.test(specSource)
  ? await (await fetch(specSource)).text()
  : readFileSync(specSource, 'utf8');
const spec = JSON.parse(specText) as Spec;

// Newest stable version <= the default per operation: what Atlas serves when
// Compass sends its single default Accept header.
const effective: Record<string, string> = Object.create(null);
for (const pathItem of Object.values(spec.paths)) {
  for (const method of METHODS) {
    const op = pathItem[method];
    if (!op?.operationId) continue;
    const versions = Object.entries(op.responses ?? {})
      .filter(([status]) => status.startsWith('2'))
      .flatMap(([, response]) => Object.keys(response.content ?? {}))
      .map((key) => VERSIONED_JSON.exec(key)?.[1])
      .filter(
        (v): v is string =>
          v !== undefined && v <= ATLAS_ADMIN_API_DEFAULT_VERSION
      )
      .sort();
    if (versions.length)
      effective[op.operationId] = versions[versions.length - 1];
  }
}

const header = `// Generated by scripts/generate-openapi-types.mts from ${specSource}. Do not edit; run \`npm run update-openapi-types\`.\n`;

writeFileSync(
  'openapi/v2.d.ts',
  header + astToString(await openapiTS(spec as never))
);
writeFileSync(
  'openapi/default-version.d.ts',
  header +
    `// Version each operation resolves to when no explicit version is requested, i.e. the newest stable one <= ATLAS_ADMIN_API_DEFAULT_VERSION (${ATLAS_ADMIN_API_DEFAULT_VERSION}).\n` +
    'export type DefaultVersion = {\n' +
    Object.entries(effective)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([op, v]) => `  readonly ${op}: '${v}';`)
      .join('\n') +
    '\n};\n'
);
