const base = require('@mongodb-js/knip-config-compass');
/** @type {import('knip').KnipConfig} */
module.exports = {
  ...base,
  entry: [
    'src/**/*.spec.{ts,tsx}',
    'tests/**/*.spec.{ts,tsx}',
    'tests/**/*.test.{ts,tsx}',
  ],
  project: ['src/**/*.{ts,tsx}', 'tests/**/*.{ts,tsx}'],
  ignoreDependencies: [
    ...base.ignoreDependencies,
    'electron',
    'ps-list',
    'puppeteer-core',
    '@electron/rebuild',
    '@mongodb-js/compass-components',
    '@mongodb-js/compass-generative-ai',
    '@mongodb-js/compass-test-server',
    '@mongodb-js/connection-info',
    '@mongodb-js/oidc-mock-provider',
    '@types/chai-as-promised',
    '@types/cross-spawn',
    '@types/yargs',
    'bson',
    'chai',
    'chai-as-promised',
    'clipboardy',
    'compass-preferences-model',
    'cross-spawn',
    'debug',
    'electron-to-chromium',
    'glob',
    'globals',
    'hadron-build',
    'jszip',
    'lodash',
    'mocha',
    'mongodb',
    'mongodb-build-info',
    'mongodb-connection-string-url',
    'mongodb-log-writer',
    'mongodb-ns',
    'node-fetch',
    'resolve-mongodb-srv',
    'semver',
    'tesseract.js',
    'tree-kill',
    'webdriverio',
    'why-is-node-running',
    'yargs',
  ],
  ignoreBinaries: [...base.ignoreBinaries, 'tsc'],
};
