const ShellApi = require('../../../../shell-api/');
const ShellEvaluator = require('../../../../shell-evaluator/').default;

/** temporal object that is used to access symbols from closures generated by browserify */
_global = {
    ShellInternalState: ShellApi.ShellInternalState,
    ShellEvaluator: ShellEvaluator,
    toShellResult: ShellApi.toShellResult,
    getShellApiType: ShellApi.getShellApiType,
};
