'use strict';

const Reflux = require('reflux');

/**
 * The actions that are handled by the data service.
 */
const Actions = Reflux.createActions([
  'aggregate',
  'aggregateComplete',
  'buildInfo',
  'buildInfoComplete',
  'connect',
  'connectComplete',
  'connectionStatus',
  'connectionStatusComplete',
  'count',
  'countComplete',
  'createCollection',
  'createCollectionComplete',
  'createIndex',
  'createIndexComplete',
  'currentOp',
  'currentOpComplete',
  'deleteMany',
  'deleteManyComplete',
  'deleteOne',
  'deleteOneComplete',
  'dropCollection',
  'dropCollectionComplete',
  'dropDatabase',
  'dropDatabaseComplete',
  'dropIndex',
  'dropIndexComplete',
  'explain',
  'explainComplete',
  'find',
  'findComplete',
  'findOneAndReplace',
  'findOneAndReplaceComplete',
  'getCollection',
  'getCollectionComplete',
  'getDatabase',
  'getDatabaseComplete',
  'getInstance',
  'getInstanceComplete',
  'hostInfo',
  'hostInfoComplete',
  'insertMany',
  'insertManyComplete',
  'insertOne',
  'insertOneComplete',
  'listCollections',
  'listCollectionsComplete',
  'listDatabases',
  'listDatabasesComplete',
  'listIndexes',
  'listIndexesComplete',
  'serverStats',
  'serverStatsComplete',
  'top',
  'topComplete',
  'updateCollection',
  'updateCollectionComplete',
  'updateMany',
  'updateManyComplete',
  'updateOne',
  'updateOneComplete',
  'usersInfo',
  'usersInfoComplete'
]);

module.exports = Actions;
