name: Connectivity tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  run_connectivity_tests:
    name: Run connectivity tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: ^12.9.0
          cache: 'npm'

      - name: Install Deps Ubuntu
        run: sudo apt-get -y install libkrb5-dev libsecret-1-dev net-tools libstdc++6 gnome-keyring

      - name: Install npm@7
        run: npm install -g npm@7

      - name: Install Dependencies
        run: npm ci

      - name: Run connectivity tests
        run: COMPASS_RUN_DOCKER_TESTS=true npm run test --workspace mongodb-data-service