name: Connectivity tests

on:
  pull_request:
  workflow_dispatch:

jobs:
  run_connectivity_tests:
    name: Run connectivity tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: ^12.9.0
          cache: 'npm'

      - name: Install Deps Ubuntu
        run: sudo apt-get -y install libkrb5-dev libsecret-1-dev net-tools libstdc++6 gnome-keyring

      - name: Install npm@7
        run: npm install -g npm@7

      - name: nslookup
        run: nslookup compass-tests.fakehost.localhost

      - name: Install Dependencies
        run: npm run bootstrap-ci

      - name: Clone docker repo
        run: |
          git clone https://github.com/mongodb-js/devtools-docker-test-envs.git
          git checkout 316790d2fbf5766d8867cb3b804546ec50f158c4
          cd devtools-docker-test-envs/docker
          docker-compose -f enterprise/docker-compose.yaml up -d
          docker-compose -f ldap/docker-compose.yaml up -d
          docker-compose -f scram/docker-compose.yaml up -d
          docker-compose -f sharded/docker-compose.yaml up -d
          docker-compose -f ssh/docker-compose.yaml up -d
          docker-compose -f tls/docker-compose.yaml up -d

      - name: Run connectivity tests
        env:
          E2E_TESTS_ATLAS_HOST: ${{ secrets.E2E_TESTS_ATLAS_HOST }}
          E2E_TESTS_DATA_LAKE_HOST: ${{ secrets.E2E_TESTS_DATA_LAKE_HOST }}
          E2E_TESTS_SERVERLESS_HOST: ${{ secrets.E2E_TESTS_SERVERLESS_HOST }}
          E2E_TESTS_ATLAS_USERNAME: ${{ secrets.E2E_TESTS_ATLAS_USERNAME }}
          E2E_TESTS_ATLAS_PASSWORD: ${{ secrets.E2E_TESTS_ATLAS_PASSWORD }}
          # Matches what we are doing in Evergreen
          MONGODB_VERSION: '4'
        run: COMPASS_RUN_DOCKER_TESTS=true npm run test --workspace mongodb-data-service
        shell: bash