name: Publish packages to npm
on:
  # NOTE: avoid using the manual execution unless is the only way to fix some issue,
  # rather retry failed jobs in case of flakes. The manual execution can potentially
  # cause the tags to point to a different commit that the one used to publish
  # the packages
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  # Used for Trusted Publishing
  # https://docs.npmjs.com/trusted-publishers#step-2-configure-your-cicd-workflow-1
  id-token: write
  # To push tags back to repo after publish
  contents: write

jobs:
  publish:
    if: |
      github.event_name == 'workflow_dispatch' ||
        startsWith(github.event.head_commit.message, 'chore(release): bump package versions')

    runs-on: ubuntu-latest

    steps:
      - uses: mongodb-js/devtools-shared/actions/setup-bot-token@main # main
        id: app-token
        with:
          app-id: ${{ vars.DEVTOOLS_BOT_APP_ID }}
          private-key: ${{ secrets.DEVTOOLS_BOT_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          # don't checkout a detatched HEAD
          ref: ${{ github.head_ref }}
          token: ${{ steps.app-token.outputs.token }}

          # this is important so git log has the whole history
          fetch-depth: '0'

      - name: 'Use Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: 24.15.0

      - name: Install npm@11.16.0
        run: npm install -g npm@11.16.0

      - name: Install Dependencies
        run: |
          npm run bootstrap-ci
        shell: bash

      - name: 'Publish what is not already in NPM'
        run: |
          npm run publish-packages

      - name: 'Publish tags'
        run: |
          npx lerna list --json | \
            jq -r '.[] | .name + "@" + .version' | \
            xargs -i sh -c "git tag -a {} -m {} || true"
          git push --follow-tags
