name: Update electron

# Runs nightly and manually
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update_generated_files:
    name: Update Electron
    runs-on: ubuntu-latest
    steps:
      - name: Create Github App Token
        uses: mongodb-js/devtools-shared/actions/setup-bot-token@main
        id: app-token
        with:
          app-id: ${{ vars.DEVTOOLS_BOT_APP_ID }}
          private-key: ${{ secrets.DEVTOOLS_BOT_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          # don't checkout a detatched HEAD
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: 20.16.0
          cache: "npm"

      - name: Install npm@10.2.4
        run: |
          npm install -g npm@10.2.4

      - name: Install Dependencies
        run: npm ci

      - name: Bump packages
        run: node scripts/update-electron.js

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # 7.0.5
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: "chore(deps): update electron"
          branch: ci/update-electron
          title: "chore(deps): update electron"
          labels: no-title-validation
          body: |
            - Update electron
