name: Update ESLint

# Runs nightly and manually
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: none # We use the github app token to push the changes

jobs:
  update_eslint:
    name: Update ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Create Github App Token
        uses: mongodb-js/devtools-shared/actions/setup-bot-token@main
        id: app-token
        with:
          app-id: ${{ vars.DEVTOOLS_BOT_APP_ID }}
          private-key: ${{ secrets.DEVTOOLS_BOT_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          # don't checkout a detatched HEAD
          ref: ${{ github.head_ref || github.ref_name }}
          token: ${{ steps.app-token.outputs.token }}

      - uses: actions/setup-node@v4
        with:
          node-version: 22.15.1
          cache: 'npm'

      - name: Install npm@10.2.4
        run: |
          npm install -g npm@10.2.4

      - name: Install dependencies
        run: |
          npm ci

      - name: Bump eslint
        run: npx compass-scripts update-dependencies preset-eslint

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5e914681df9dc83aa4e4905692ca88beb2f9e91f # 7.0.5
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: 'chore(deps): update eslint'
          branch: ci/update-eslint
          title: 'chore(deps): update eslint'
          labels: no-title-validation
          author: '${{ steps.app-token.outputs.app-slug}}[bot] <${{ steps.app-token.outputs.app-email }}>'
          body: |
            - Update ESLint to latest 8
